name: steffbeckers

services:
  mailhog:
    image: mailhog/mailhog
    container_name: steffbeckers_mailhog
    restart: always
    ports:
      - 25:1025
    logging:
      driver: 'none'
    networks:
      - steffbeckers
  nginx:
    image: nginx
    container_name: steffbeckers_nginx
    depends_on:
      - mailhog
      - rabbitmq
      - redis
      - redis-commander
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/api.conf:/etc/nginx/api.conf:ro
      - ./nginx/etc/nginx/common.conf:/etc/nginx/common.conf:ro
      - ./nginx/etc/nginx/common_location.conf:/etc/nginx/common_location.conf:ro
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/etc/nginx/ssl.conf:/etc/nginx/ssl.conf:ro
      - ./nginx/etc/ssl/certs/steffbeckers.localhost.crt:/etc/ssl/certs/steffbeckers.localhost.crt:ro
      - ./nginx/etc/ssl/private/steffbeckers.localhost.key:/etc/ssl/private/steffbeckers.localhost.key:ro
      - ./nginx/var/www:/var/www
    networks:
      - steffbeckers
    extra_hosts:
      - "host.docker.internal:host-gateway"
  rabbitmq:
    image: rabbitmq:management
    container_name: steffbeckers_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=steffbeckers
      - RABBITMQ_DEFAULT_PASS=Pqdky8ozQBww7tqyi!hM
    ports:
      - 5672:5672
    networks:
      - steffbeckers
  redis:
    image: redis
    container_name: steffbeckers_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - steffbeckers
  redis-commander:
    image: rediscommander/redis-commander
    container_name: steffbeckers_redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - steffbeckers

networks:
  steffbeckers:
    name: steffbeckers
