name: steffbeckers

services:
  mailhog:
    image: mailhog/mailhog
    container_name: steffbeckers_mailhog
    restart: always
    logging:
      driver: none
    networks:
      - steffbeckers
  nginx:
    image: nginx
    container_name: steffbeckers_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/api.conf:/etc/nginx/api.conf:ro
      - ./nginx/etc/nginx/common.conf:/etc/nginx/common.conf:ro
      - ./nginx/etc/nginx/common_location.conf:/etc/nginx/common_location.conf:ro
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/etc/nginx/ssl.conf:/etc/nginx/ssl.conf:ro
      - ./nginx/etc/ssl/certs/steffbeckers.local.crt:/etc/ssl/certs/steffbeckers.local.crt:ro
      - ./nginx/etc/ssl/private/steffbeckers.local.key:/etc/ssl/private/steffbeckers.local.key:ro
      - ./nginx/var/www/html:/var/www/html
    networks:
      - steffbeckers
  rabbitmq:
    image: rabbitmq:management
    container_name: steffbeckers_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=steff
      - RABBITMQ_DEFAULT_PASS=Pqdky8ozQBww7tqyi!hM
    networks:
      - steffbeckers
  redis:
    image: redis
    container_name: steffbeckers_redis
    restart: always
    networks:
      - steffbeckers
  redis-commander:
    depends_on:
      - redis
    image: rediscommander/redis-commander
    container_name: steffbeckers_redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - steffbeckers

networks:
  steffbeckers:
    name: steffbeckers
