name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angular
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx-cloud record -- npx nx affected -t lint test build
