name: Angular CI

on:
  push:
    branches:
      - main
    # TODO
    # paths:
    #   - angular/**
  pull_request:
    paths:
      - angular/**

env:
  NX_WORKSPACE_ROOT_PATH: angular/

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx-cloud record -- npx nx affected -t lint test build
